# Generated by Django 5.1.15 on 2026-08-27 07:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Nombre de la Empresa')),
                ('sector', models.CharField(blank=True, default='General / Comercial', max_length=150, verbose_name='Sector')),
                ('nit', models.CharField(blank=True, default='', max_length=50, verbose_name='NIT / Identificación Tributaria')),
                ('ciudad', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('sitio_web', models.CharField(blank=True, default='', max_length=255, verbose_name='Sitio Web')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('nombre_completo', models.CharField(db_index=True, max_length=255, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono / Celular')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Electrónico')),
                ('rol', models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo / Rol')),
                ('tipo_persona', models.CharField(blank=True, choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=20, verbose_name='Tipo de Persona')),
                ('tipo_relacion', models.CharField(blank=True, choices=[('prospecto', 'Prospecto / Lead'), ('cliente_bronze', 'Cliente Bronze'), ('cliente_silver', 'Cliente Silver'), ('cliente_gold', 'Cliente Gold'), ('cliente_platinum', 'Cliente Platinum'), ('aliado', 'Aliado Estratégico'), ('proveedor', 'Proveedor'), ('interno', 'Equipo Interno / CNTXT'), ('otro', 'Otro')], default='prospecto', max_length=30, verbose_name='Tipo de Relación')),
                ('canal_entrada', models.CharField(blank=True, choices=[('referido', 'Referido / Recomendación'), ('whatsapp', 'WhatsApp Directo'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('feria_evento', 'Feria / Evento Comercial'), ('web', 'Sitio Web'), ('directo', 'Contacto Directo / Networking'), ('otro', 'Otro')], default='directo', max_length=30, verbose_name='Canal de Entrada')),
                ('pulso_vital', models.PositiveSmallIntegerField(choices=[(1, '1 - Pulso Bajo / En Frío'), (2, '2 - Pulso Estable / Tibio'), (3, '3 - Pulso Activo / Caliente'), (4, '4 - Pulso Vital / Máxima Prioridad')], default=1, help_text='Nivel de calor/pulso vital del contacto (1 al 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Pulso Vital (1 al 4)')),
                ('fase_red', models.CharField(choices=[('R', 'R - Relación / Reconocimiento'), ('D', 'D - Desarrollo / Decisión'), ('E', 'E - Estructuración / Ejecución')], default='R', max_length=1, verbose_name='Fase R.E.D. (R, D, E)')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('titulo', models.CharField(db_index=True, max_length=255, verbose_name='Título del Proyecto')),
                ('monto_proyectado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Proyectado ($)')),
                ('estado', models.CharField(choices=[('mql', '🩸 MQL | Plasma (10%)'), ('conversacion', '💓 1ra Conversación (20%)'), ('sql', '🔬 SQL | Válvula (40%)'), ('propuesta', '⚡ Propuesta Presentada (60%)'), ('negociacion', '🫀 En Negociación (80%)'), ('ejecucion', '🧬 Tejido Consolidado (100%)'), ('pausa', '⏸️ Estasis / Pausa (0%)')], db_index=True, default='mql', max_length=20, verbose_name='Estado del Pipeline')),
                ('linea_operativa', models.CharField(blank=True, choices=[('cor_lo_01', 'C.O.R. | LO. 0.1. Estructuración y Gerencia'), ('cor_lo_02', 'C.O.R. | L.O. 02. Diseño Arquitectónico'), ('cor_lo_03', 'C.O.R. | L.O. 03. Visualización Arquitectónica'), ('cor_lo_04', 'C.O.R. | L.O. 04. Tecnología y Ux'), ('cor_lo_05', 'C.O.R. | L.O. 05. Gestión Urbana'), ('cor_lo_06', 'C.O.R. | L.O. 06. Construcción de Proyectos'), ('cor_lo_07', 'C.O.R. | L.O. 07. Educación y Formación')], default='', max_length=50, verbose_name='Línea Operativa (C.O.R.)')),
                ('categoria', models.CharField(blank=True, choices=[('cor_cat_01', 'C.O.R. | 01. Parcelaciones y Condominios'), ('cor_cat_02', 'C.O.R. | 02. Edificación en Altura'), ('cor_cat_03', 'C.O.R. | 03. Vivienda Campestre'), ('cor_cat_04', 'C.O.R. | 04. Comercial'), ('cor_cat_08', 'C.O.R. | 08. Hotelería y Hospitality')], default='', max_length=50, verbose_name='Categoría (C.O.R.)')),
                ('brief_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Link del Brief')),
                ('proposal_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Link de la Propuesta')),
                ('proximo_paso', models.CharField(blank=True, default='', max_length=255, verbose_name='Próximo Paso / Next Step')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite / Due Date')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='core.contacto', verbose_name='Contacto Principal')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
