# Generated by Django 5.1.15 on 2026-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad / País'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='canal_entrada',
            field=models.CharField(blank=True, choices=[('referido', 'Referido / Recomendación'), ('referidos', 'Referidos'), ('whatsapp', 'WhatsApp Directo'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('feria_evento', 'Feria / Evento Comercial'), ('ferias', 'Ferias o Activaciones'), ('web', 'Sitio Web'), ('directo', 'Contacto Directo / Networking'), ('prospeccion', 'Prospección Activa'), ('oficinas', 'Oficinas CNTXT'), ('capital', 'Capital Relacional'), ('fb', 'Media | Facebook'), ('ig', 'Media | Instagram'), ('gg', 'Media | Google'), ('gmaps', 'Media | Google Maps'), ('otro', 'Otro')], default='directo', max_length=30, verbose_name='Canal de Entrada'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica'), ('b2c', 'Persona Natural (B2C)'), ('b2b', 'Persona Jurídica (B2B)')], default='natural', max_length=20, verbose_name='Tipo de Persona'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_relacion',
            field=models.CharField(blank=True, choices=[('prospecto', 'Prospecto'), ('lead', 'Lead / Prospecto'), ('growth', 'Growth Partner'), ('cliente_black', 'Cliente Black'), ('cliente_gold', 'Cliente Gold'), ('cliente_silver', 'Cliente Silver'), ('cliente_bronze', 'Cliente Bronze'), ('embajador', 'Embajador de Marca'), ('aliado', 'Aliado Estratégico'), ('aliados', 'Aliados Estratégicos'), ('proveedor', 'Proveedor'), ('interno', 'Equipo Interno / CNTXT'), ('equipo', 'Equipo CNTXT'), ('media', 'Media & Influencers'), ('servicios_claves', 'Servicios Claves'), ('servicios_aux', 'Servicios Auxiliares'), ('candidatos', 'Candidatos y Talento'), ('mentores', 'Mentores y Asesores'), ('otro', 'Otro')], default='prospecto', max_length=30, verbose_name='Tipo de Relación'),
        ),
    ]
