# Generated by Django 5.1.15 on 2026-09-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto_ciudad_alter_contacto_canal_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='pais',
            field=models.CharField(blank=True, default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='primer_nombre',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Primer Nombre'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='segundo_nombre',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad'),
        ),
    ]
