# Generated by Django 5.1.15 on 2026-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto_apellidos_contacto_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='siguiente_accion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Siguiente Acción / Próximo Paso'),
        ),
    ]
