# Generated by Django 5.1.15 on 2026-09-17 06:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_siguiente_accion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('tipo', models.CharField(choices=[('contacto_creado', 'Contacto Creado'), ('contacto_editado', 'Contacto Editado'), ('contacto_eliminado', 'Contacto Eliminado'), ('empresa_creada', 'Empresa Creada'), ('empresa_editada', 'Empresa Editada'), ('empresa_eliminada', 'Empresa Eliminada'), ('proyecto_creado', 'Proyecto Creado'), ('proyecto_editado', 'Proyecto Editado'), ('proyecto_eliminado', 'Proyecto Eliminado'), ('pulso_evaluado', 'Pulso Relacional Evaluado'), ('estado_cambiado', 'Estado de Proyecto Cambiado'), ('login', 'Inicio de Sesión'), ('otro', 'Otra Actividad')], db_index=True, default='otro', max_length=30, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='core.contacto', verbose_name='Contacto Relacionado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='core.empresa', verbose_name='Empresa Relacionada')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='core.proyecto', verbose_name='Proyecto Relacionado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('rol', models.CharField(choices=[('superadmin', 'Superadmin'), ('ceo_coo', 'CEO / COO'), ('coordinadora', 'Coordinadora'), ('director', 'Director'), ('growth_partner', 'Growth Partner')], default='growth_partner', max_length=30, verbose_name='Rol en el Sistema')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PulsoRelacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('afinidad_adn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('25'))], verbose_name='Afinidad ADN (0-25)')),
                ('recomendar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('25'))], verbose_name='Recomendar / Advocacy (0-25)')),
                ('bidireccionalidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='Bidireccionalidad (0-20)')),
                ('vulnerabilidad_sandler', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Vulnerabilidad Sandler (0-10)')),
                ('insider_cialdini', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Insider Cialdini / Comunidad (0-10)')),
                ('mapa_de_vida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Mapa de Vida / Claridad (0-10)')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas de la Evaluación')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_pulso', to='core.contacto', verbose_name='Contacto Evaluado')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado Por')),
            ],
            options={
                'verbose_name': 'Pulso Relacional',
                'verbose_name_plural': 'Pulsos Relacionales',
                'ordering': ['-created_at'],
            },
        ),
    ]
