# Generated by Django 5.1.15 on 2026-09-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_actividad_perfilusuario_pulsorelacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='flujo',
            field=models.CharField(choices=[('b2b', 'Flujo de Proyectos MADE B2B'), ('b2c', 'Proyectos MADE B2C'), ('select', 'Proyectos SELECT'), ('showroom', 'ShowRoom CNTXT')], db_index=True, default='b2b', max_length=20, verbose_name='Flujo de Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('mql', '🩸 MQL | Plasma (10%)'), ('conversacion', '💓 1ra Conversación (20%)'), ('sql', '🔬 SQL | Válvula (40%)'), ('propuesta', '⚡ Propuesta Presentada (60%)'), ('negociacion', '🫀 En Negociación (80%)'), ('ejecucion', '🧬 Tejido Consolidado (100%)'), ('pausa', '⏸️ Estasis / Pausa (0%)'), ('b2c_sueno', '🏡 Sueño Familiar | MQL (10%)'), ('b2c_visita', '🌿 Visita a Lote / Entrevista (20%)'), ('b2c_anteproyecto', '📐 Diagnóstico & Concepto (40%)'), ('b2c_propuesta', '✨ Propuesta de Diseño (60%)'), ('b2c_acuerdo', '🤝 Decisión Familiar (80%)'), ('b2c_obra', '🏗️ Hogar en Construcción (100%)'), ('b2c_pausa', '⏸️ Proyecto en Pausa (0%)'), ('sel_lead', '⚡ Lead Catálogo (15%)'), ('sel_seleccion', '📋 Selección Modelo (35%)'), ('sel_cotizacion', '📑 Orden & Paquete (60%)'), ('sel_cierre', '🚀 Compra & Entrega (100%)'), ('sel_pausa', '⏸️ Descartado / Pausa (0%)'), ('shw_prospecto', '🎯 Prospecto Interesado (10%)'), ('shw_experiencia', '🏛️ Visita / Recorrido (25%)'), ('shw_separacion', '🔒 Separación de Unidad (50%)'), ('shw_promesa', '✍️ Promesa Compraventa (75%)'), ('shw_escritura', '🔑 Escrituración & Entrega (100%)'), ('shw_desistido', '⏸️ Desistido / Pausa (0%)')], db_index=True, default='mql', max_length=50, verbose_name='Estado del Pipeline'),
        ),
    ]
