# Generated by Django 5.1.15 on 2026-10-05 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proyecto_flujo_alter_proyecto_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('id', models.CharField(help_text='Identificador único del proyecto (e.g. proj-1728157000000 o UUID)', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('category', models.CharField(blank=True, default='general', max_length=100, verbose_name='Categoría')),
                ('color', models.CharField(blank=True, default='#7928ca', max_length=50, verbose_name='Color de Identificación')),
                ('tasks', models.JSONField(blank=True, default=list, verbose_name='Listado de Tareas y Subtareas Jerárquicas')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_projects', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('crm_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_projects', to='core.proyecto', verbose_name='Proyecto CRM Vinculado')),
            ],
            options={
                'verbose_name': 'Proyecto de Checklist',
                'verbose_name_plural': 'Proyectos de Checklist',
                'ordering': ['-updated_at'],
            },
        ),
    ]
