# Generated by Django 5.1.15 on 2026-09-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proyecto_flujo_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='bitacora',
            field=models.JSONField(blank=True, default=list, verbose_name='Bitácora de Trazabilidad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Responsable / Owner'),
        ),
    ]
