# Generated by Django 5.1.15 on 2026-10-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_checklistproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksTeamMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('id', models.CharField(help_text='Correo electrónico o identificador único del miembro', max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Corto')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('role', models.CharField(blank=True, default='Miembro', max_length=150, verbose_name='Rol')),
                ('avatar', models.TextField(blank=True, default='', verbose_name='URL o Base64 de Avatar')),
                ('initials', models.CharField(blank=True, default='', max_length=10, verbose_name='Iniciales')),
                ('color', models.CharField(blank=True, default='#C8A87A', max_length=50, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Miembro de Equipo Tasks',
                'verbose_name_plural': 'Miembros de Equipo Tasks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='checklistproject',
            name='sistema_id_str',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID de Sistema en Frontend'),
        ),
        migrations.CreateModel(
            name='ChecklistSystem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('id', models.CharField(help_text='Identificador único del sistema (e.g. sys-1728157000000 o UUID)', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Sistema')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='Código o Sigla')),
                ('color', models.CharField(blank=True, default='#C8A87A', max_length=50, verbose_name='Color Distintivo')),
                ('icon', models.CharField(blank=True, default='layers', max_length=50, verbose_name='Ícono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_systems', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Sistema de Gestión',
                'verbose_name_plural': 'Sistemas de Gestión',
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='checklistproject',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='core.checklistsystem', verbose_name='Sistema al que pertenece'),
        ),
    ]
