# Generated by Django 5.2.17 on 2026-08-19 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_label', models.CharField(help_text="Ej. 'KR 1 · Adopción COR' o 'NEO_VCD'", max_length=60)),
                ('text', models.TextField()),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Peso dentro del promedio del objetivo')),
                ('evolution_tag', models.CharField(blank=True, choices=[('', '—'), ('nuevo', 'Nuevo'), ('evoluciona', 'Evoluciona'), ('consolida', 'Consolida'), ('mantiene', 'Mantiene')], max_length=12)),
                ('status_note', models.CharField(blank=True, help_text="Ej. 'Ventana: Julio'", max_length=150)),
                ('extra_note', models.TextField(blank=True)),
                ('confidence', models.CharField(blank=True, choices=[('', 'Sin evaluar'), ('verde', 'Verde — en curso'), ('ambar', 'Ámbar — en riesgo'), ('rojo', 'Rojo — bloqueado')], max_length=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('color_hex', models.CharField(help_text='Ej. #A67C52', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='okr.keyresult')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target', models.FloatField()),
                ('unit', models.CharField(blank=True, help_text="Ej. '%', 'COP', '#'", max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='okr.keyresult')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='okr.kpi')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LineCyclePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('definido', 'Definido'), ('parcial', 'Parcial'), ('pendiente', 'Pendiente de definir')], default='pendiente', max_length=12)),
                ('intro_text', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True, help_text='Cuadro de Mando Integral')),
                ('deliverable', models.CharField(blank=True, max_length=200)),
                ('lead_label', models.CharField(blank=True, max_length=120)),
                ('closing_quote', models.TextField(blank=True)),
                ('closing_quote_label', models.CharField(blank=True, max_length=120)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_plans', to='okr.cycle')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='okr.line')),
            ],
            options={
                'ordering': ['line__order'],
                'unique_together': {('line', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej. O1, O.T.1', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('owner_label', models.CharField(blank=True, max_length=150)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Peso dentro del promedio de la línea')),
                ('priority', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('is_backlog', models.BooleanField(default=False, help_text='Backlog: posible desarrollo, no prioritario este ciclo')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('aligns_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aligned_children', to='okr.objective')),
                ('line_cycle_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='okr.linecycleplan')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr.objective'),
        ),
    ]
