# Generated by Django 5.2.15 on 2026-08-21 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Acción', 'verbose_name_plural': 'Acciones'},
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Check-in', 'verbose_name_plural': 'Check-ins'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['-starts_on'], 'verbose_name': 'Ciclo', 'verbose_name_plural': 'Ciclos'},
        ),
        migrations.AlterModelOptions(
            name='keyresult',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Key Result', 'verbose_name_plural': 'Key Results'},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['order', 'id'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['order', 'code'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas'},
        ),
        migrations.AlterModelOptions(
            name='linecycleplan',
            options={'ordering': ['line__order'], 'verbose_name': 'Plan de línea', 'verbose_name_plural': 'Planes de línea'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['order', 'code'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Hecho'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='key_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='okr.keyresult', verbose_name='Key Result'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='okr.kpi', verbose_name='KPI'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='ends_on',
            field=models.DateField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='starts_on',
            field=models.DateField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='confidence',
            field=models.CharField(blank=True, choices=[('', 'Sin evaluar'), ('verde', 'Verde — en curso'), ('ambar', 'Ámbar — en riesgo'), ('rojo', 'Rojo — bloqueado')], max_length=6, verbose_name='Confianza'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='evolution_tag',
            field=models.CharField(blank=True, choices=[('', '—'), ('nuevo', 'Nuevo'), ('evoluciona', 'Evoluciona'), ('consolida', 'Consolida'), ('mantiene', 'Mantiene')], max_length=12, verbose_name='Evolución'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='extra_note',
            field=models.TextField(blank=True, verbose_name='Nota adicional'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr.objective', verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='status_note',
            field=models.CharField(blank=True, help_text="Ej. 'Ventana: Julio'", max_length=150, verbose_name='Nota de estado'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='tag_label',
            field=models.CharField(help_text="Ej. 'KR 1 · Adopción COR' o 'NEO_VCD'", max_length=60, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Peso dentro del promedio del objetivo', verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='key_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='okr.keyresult', verbose_name='Key Result'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target',
            field=models.FloatField(verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='unit',
            field=models.CharField(blank=True, help_text="Ej. '%', 'COP', '#'", max_length=20, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='line',
            name='code',
            field=models.SlugField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='line',
            name='color_hex',
            field=models.CharField(help_text='Ej. #A67C52', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='line',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='line',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='closing_quote',
            field=models.TextField(blank=True, verbose_name='Cita de cierre'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='closing_quote_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Etiqueta de la cita'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_plans', to='okr.cycle', verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='deliverable',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entregable'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='lead_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Líder'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='okr.line', verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='status',
            field=models.CharField(choices=[('definido', 'Definido'), ('parcial', 'Parcial'), ('pendiente', 'Pendiente de definir')], default='pendiente', max_length=12, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='linecycleplan',
            name='summary_text',
            field=models.TextField(blank=True, help_text='Cuadro de Mando Integral', verbose_name='Cuadro de Mando Integral'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='aligns_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aligned_children', to='okr.objective', verbose_name='Alinea a'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='code',
            field=models.CharField(help_text='Ej. O1, O.T.1', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='is_backlog',
            field=models.BooleanField(default=False, help_text='Backlog: posible desarrollo, no prioritario este ciclo', verbose_name='Backlog'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='line_cycle_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='okr.linecycleplan', verbose_name='Plan de línea'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='owner_label',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='priority',
            field=models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Peso dentro del promedio de la línea', verbose_name='Peso'),
        ),
    ]
