# Generated by Django 5.2.15 on 2026-08-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_alter_actionitem_options_alter_checkin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecycleplan',
            name='summary_text',
            field=models.TextField(blank=True, help_text='Objetivo del ciclo', verbose_name='Objetivo del ciclo'),
        ),
    ]
