# Generated by Django 5.2.15 on 2026-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0003_alter_linecycleplan_summary_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='baseline',
            field=models.FloatField(default=0, help_text='Desde dónde partís. Permite medir avance aunque la meta sea bajar (incluso a negativo).', verbose_name='Valor de inicio'),
        ),
    ]
